# Server configuration
server.port=8080
#server.port=8081

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/studs
spring.datasource.username=s381032
spring.datasource.password=UVos.8847
#spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/mts
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# Payment service configuration
payment.service.url=http://timoapp.tech:8000/api/v1/payments/process

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Allow circular references
spring.main.allow-circular-references=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
