# Server configuration
#server.port=8080
server.port=8081

# Database configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/studs
#spring.datasource.username=s381032
#spring.datasource.password=UVos.8847
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/mts
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# YooMoney (ЮKassa) configuration
yoomoney.shop.id=${YOOMONEY_SHOP_ID}
yoomoney.secret.key=${YOOMONEY_SECRET_KEY}
yoomoney.api.url=https://api.yookassa.ru/v3/payments

# Payment service configuration
# payment.service.url=http://timoapp.tech:8000/api/v1/payments/process

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Allow circular references
spring.main.allow-circular-references=true

# Logging
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO
logging.level.ru.sashil=DEBUG
